version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - rust
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - go
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /manager
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - kotlin
      - gradle
    groups:
      gradle-dependencies:
        patterns:
          - "*"